"""Initial accounts documents and analysis schema

Revision ID: 80e4e1f99f1d
Revises:
Create Date: 2026-10-05 20:55:02.133572

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "80e4e1f99f1d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_login", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("page_texts", sa.JSON(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("sentence_count", sa.Integer(), nullable=False),
        sa.Column("paragraph_count", sa.Integer(), nullable=False),
        sa.Column("unique_word_count", sa.Integer(), nullable=False),
        sa.Column("reading_time", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("extraction_method", sa.String(length=30), nullable=False),
        sa.Column("warning", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_filename"),
    )
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("common_words", sa.JSON(), nullable=False),
        sa.Column("longest_words", sa.JSON(), nullable=False),
        sa.Column("shortest_words", sa.JSON(), nullable=False),
        sa.Column("lexical_diversity", sa.Float(), nullable=False),
        sa.Column("average_word_length", sa.Float(), nullable=False),
        sa.Column("average_sentence_length", sa.Float(), nullable=False),
        sa.Column("characters_without_spaces", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("analysis")
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_user_id"))
        batch_op.drop_index(batch_op.f("ix_document_created_at"))

    op.drop_table("document")
    op.drop_table("user")
    # ### end Alembic commands ###
